Updating data model
DiSSCo/handle-manager pull request #5
Opened 2022-11-14 15:00 UTC by southeo

Updating data model

2022-11-16 10:06 UTC, samleeflang reviewed
Hi Sou,
Nice work, there are a lot of things in there that we need.
It is your first reviewed PR so part of the comments are about conventions.
It also reminds me that we haven't written these down which might be a good idea.
I will plan an hour tomorrow where we can run through them in person and see what we can do differently.
We can then also walk through the outstanding Sonar issues

2022-11-16 10:06 UTC, samleeflang commented on src/test/java/com/example/handlemanager/service/PidTypeServiceTest.java
> +	private MockedStatic mockedStatic;
Don't think it is used here

2022-11-16 10:06 UTC, samleeflang commented on src/test/java/com/example/handlemanager/service/PidTypeServiceTest.java
> +	private String pid;
Don't think these need to be uninitiated private class variables

2022-11-16 10:06 UTC, samleeflang commented on src/test/java/com/example/handlemanager/service/PidTypeServiceTest.java
> +		//CREATED_INSTANT.getEpochSecond();
Remove comment

2022-11-16 12:10 UTC, southeo commented on pom.xml
>  	<groupId>com.example</groupId>
So have:  `<groupId>eu.dissco</groupId>` ? Yes that makes sense

2022-11-16 12:20 UTC, southeo commented on pom.xml
>      		<groupId>org.glassfish.jersey.core</groupId> <!-- Response Package 2-->
I think this was related to when I introduced openFeign - not needed any more & removed

2022-11-16 12:22 UTC, southeo commented on pom.xml
> +    		<groupId>com.h2database</groupId>
Not anymore

2022-11-16 12:28 UTC, southeo commented on src/main/java/com/example/handlemanager/configuration/Config.java
> +		return Clock.systemUTC();
I think the default is actually `Clock.systemDefaultZone()`

2022-11-16 13:05 UTC, southeo commented on src/main/java/com/example/handlemanager/domain/requests/DigitalSpecimenBotanyRequest.java
> +	final String objectType;
@value makes the class itself final. There's a lot of inheritance with these request classes, so that's not ideal. I'll just go with @Getter for now and see if I need more lombok functionality.

2022-11-16 14:44 UTC, southeo commented on src/main/java/com/example/handlemanager/repository/HandleRepository.java
> +	@Query(value="select distinct handle from handles h", nativeQuery=true)
Good catch, added basic pagination for now (will change when jooq is implemented though)

2022-11-16 15:19 UTC, southeo commented on src/main/java/com/example/handlemanager/service/PidTypeService.java
> +			e.printStackTrace();
Handled by controller now

2022-11-16 15:31 UTC, southeo commented on src/main/java/com/example/handlemanager/service/PidTypeService.java
> +		String typeJson = "";
I'm not quite sure which info you're talking about. 
There are a few fields in the pid record that are themselves json-formatted strings of pid records of types. The strings are in the following format: 
{
"pid": "10.20/ABC-123",
"pidType: "<handle or doi>"
"primaryNameFromPid":"<Institution Name>"
}

This class uses the pid of the type record provided in the request (i.e. 10.20/ABC-123) to resolve the full record and create the above string. 

Do you mean should this string be in the database? I don't think it should. 

A better way of doing this would be creating a POJO with these fields and using an object mapper to generate the string.

2022-11-16 16:10 UTC, southeo commented on src/main/java/com/example/handlemanager/service/PidTypeService.java
> +			typeJson = "{ \n" + "\"pid\": \"" + pid + NEWLINE + "\"pidType\": \"" + pidType + NEWLINE
Done

2022-11-16 16:10 UTC, southeo commented on src/main/java/com/example/handlemanager/service/PidTypeService.java
> +		String typeJson = "";
Ignore the comment about pojo, objectNode is way better

2022-11-28 09:45 UTC, samleeflang requested changes
Looking good, couple of things and then this can be merged

2022-11-28 09:45 UTC, samleeflang commented on pom.xml
> +  <description>API for adding handle records</description>
Normally these go on top.
Then dependencies followed by plugins.
Is better for readability and maintainability as you first get the name, parent, and versions

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/controller/HandleController.java
> +    return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
Maybe use another return code.
Then 400 range is for exception because there is some condition invalid and you 'expected' this exception.
The 500 range is something happend that you did not anticipate and you don't know why.
For more on the difference:
https://enterprisecraftsmanship.com/posts/rest-api-response-codes-400-vs-500/#:~:text=The%20main%20difference%20between%20the,itself%20who%20caused%20the%20problem.

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/domain/requests/DigitalSpecimenBotanyRequest.java
> +@JsonIgnoreProperties
Why is this needed?

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/domain/requests/HandleRecordRequest.java
> +  public boolean equals(Object o) {
This doesn't inherit any method so I think the lombok annotation can be used, although for consistency it might be good  to keep the methods in full

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/domain/requests/HandleRecordRequest.java
> +  protected final String pidIssuerPid;
Can these be private final variables?

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/domain/responses/DigitalSpecimenBotanyResponse.java
> +@Data
I think these can be the same as the others right? Only Getters and the constructor for init. The variables can then become private final.

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/domain/responses/DigitalSpecimenResponse.java
> +@Data
I think these can be the same as the others right? Only Getters and the constructor for init. The variables can then become private final.

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/domain/responses/DoiRecordResponse.java
> +@Data
I think these can be the same as the others right? Only Getters and the constructor for init. The variables can then become private final.

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/domain/responses/DigitalSpecimenResponse.java
> +    String type;
I don't get this constructor.
You are overwriting the type multiple times right?
Say entry 1 is type 'A' and entry 2 is type 'B' then the type and data is overwritten.
I have the feeling that you are creating one object while it should be many.

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/domain/responses/HandleRecordResponse.java
> +        default -> log.info("Base constructor called");
Not really where default is for, I would break when the case is met and use default to indicate that none of the above cases matches. The log statement (although I would probably not put one here) at the top of the constructor

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/HandleGeneratorService.java
> +  @Autowired
No longer needed

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/HandleGeneratorService.java
> +  public HandleGeneratorService() {
I think this could conflict with the annotation. For not hardcode these with the variable and maybe make a task to create a properties class where we can change them for env variables.

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
> +    List<Handles> doiRecord;
Why not init this variable in the loop so that it is just instantiated there and you don't have to clear?

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
> +    List<Handles> digitalSpecimenRecord;
Why not init this variable in the loop so that it is just instantiated there and you don't have to clear?

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
> +    List<Handles> digitalSpecimenBotanyRecord;
Why not init this variable in the loop so that it is just instantiated there and you don't have to clear?

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
> +    List<Handles> handleRecord;
Instantiation is on next line, combine statements

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
> +    List<Handles> handleRecord;
Instantiation is on next line, combine statements

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
> +    List<Handles> handleRecord;
Instantiation is on next line, combine statements

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/HandleService.java
> +    List<Handles> handleRecord;
Instantiation is on next line, combine statements

2022-11-28 09:45 UTC, samleeflang commented on src/main/java/eu/dissco/core/handlemanager/service/PidTypeService.java
> +    return ""; // This should maybe return a warning?
Agree probably a log.error and maybe an exception but at least log that something unexpected happend

2022-11-28 09:45 UTC, samleeflang commented on src/test/java/eu/dissco/core/handlemanager/controller/HandleControllerTest.java
> +      throws PidCreationException, PidResolutionException, JsonProcessingException, ParserConfigurationException, TransformerException {
For these test methods you could also just `throws Exception`

2022-11-28 09:45 UTC, samleeflang commented on src/test/java/eu/dissco/core/handlemanager/service/HandleGeneratorServiceTest.java
> +  @InjectMocks
You probably want to test with the actual service

2022-11-28 09:45 UTC, samleeflang commented on src/test/java/eu/dissco/core/handlemanager/service/HandleServiceTest.java
> +    log.info("tbf is null: " + String.valueOf(documentBuilderFactory == null));
Is this needed, the documentBuilderFactor is always null right? as it isn't initiated

2022-11-28 09:45 UTC, samleeflang commented on src/test/java/eu/dissco/core/handlemanager/service/HandleServiceTest.java
> +
Sometimes there are some unnecessary white lines in your code

2022-11-28 09:45 UTC, samleeflang commented on src/test/java/eu/dissco/core/handlemanager/service/PidTypeServiceTest.java
> +  ObjectMapper mapper;
Doesn't need to be declared here

2022-11-29 14:16 UTC, southeo commented on src/main/java/eu/dissco/core/handlemanager/domain/requests/HandleRecordRequest.java
> +  public boolean equals(Object o) {
I'd like to keep them consistent

2022-11-29 14:22 UTC, southeo commented on src/main/java/eu/dissco/core/handlemanager/domain/responses/DigitalSpecimenResponse.java
> +    String type;
Resolving because I removed this constructor when I implemented Jooq

(To clarify: the intention was that each "entries" object have a different "type"; the list provided was the same thing as a single handle record. So one entry might be [type: "pidStatus", data: "DRAFT"], then the next would be [type: "digitalObjectType", data: "Botany Specimen"], etc.

2022-11-29 14:44 UTC, southeo commented on src/test/java/eu/dissco/core/handlemanager/controller/HandleControllerTest.java
> +      throws PidCreationException, PidResolutionException, JsonProcessingException, ParserConfigurationException, TransformerException {
Done

2022-11-29 14:45 UTC, southeo commented on src/main/java/eu/dissco/core/handlemanager/service/HandleGeneratorService.java
> +  public HandleGeneratorService() {
Fixed + added task to jira

2022-11-29 14:46 UTC, southeo commented on src/main/java/eu/dissco/core/handlemanager/domain/responses/HandleRecordResponse.java
> +        default -> log.info("Base constructor called");
Resolved because this is removed in update

2022-11-29 14:46 UTC, southeo commented on src/main/java/eu/dissco/core/handlemanager/domain/responses/DoiRecordResponse.java
> +@Data
Replaced all classes with getter and constructor tags

2022-11-29 14:50 UTC, southeo commented on src/test/java/eu/dissco/core/handlemanager/service/HandleGeneratorServiceTest.java
> +  @InjectMocks
Resolved because this issue is fixed in the Jooq branch

2022-11-29 14:52 UTC, southeo reviewed
I'm removing some tests from this PR. I rewrote most of the tests to comply with Jooq in the next PR.

2022-11-29 15:27 UTC, southeo commented on src/main/java/eu/dissco/core/handlemanager/controller/HandleController.java
> +    return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
Oh I didn't know the difference between these two ranges, that's interesting. Marked as 400 BAD REQUEST.

2022-11-29 15:45 UTC, southeo commented on src/main/java/eu/dissco/core/handlemanager/domain/requests/DigitalSpecimenBotanyRequest.java
> +@JsonIgnoreProperties
I thought this prevented an UnknownFieldException, in case a field from a DoiRequest was included in a HandleRequest. But I can't seem to trigger that error now...
Removed

2022-11-29 15:52 UTC, southeo commented on src/test/java/eu/dissco/core/handlemanager/service/PidTypeServiceTest.java
> +  ObjectMapper mapper;
Are you sure? this is an injected bean.

2022-11-29 16:05 UTC, southeo commented
PR is reviewed. All changes that have been implemented have been resolved; anything outstanding is remaining (a few comments). Mostly, there are a few things that I have already fixed downstream in the JOOQ branch, so I didn't touch them in this branch. Thanks for the feedback.

2022-11-30 08:01 UTC, samleeflang commented on src/test/java/eu/dissco/core/handlemanager/service/PidTypeServiceTest.java
> +  ObjectMapper mapper;
No it is not here as this is a test class where we only Mock things but don't inject. Here it is just an uninstantiated variable. In the constructor you instantiate it an pass it to the service but in the test itself is not used. So this can be removed here and only be instantiated and used in the constructor.

2022-11-30 08:03 UTC, samleeflang approved these changes
Ok thanks for picking up the comments! Have a few left but let's do those in the JOOQ PR and I will approve this on. One additional comment is that sometimes a multiple new lines are used which doesn't break the code but for consistency just use one between methods.
- HandleController on line 152 still returns a 500. We don't throw the 500 if we expect an error which is here so better to use a 4XX
- Instead of questions or TODO in the code create a task on the backlog, so the comment on HandleService 362 can be removed. Don't think there is a converter, however this would be a place to use a stream. Something like bytelist.toStream().map(byteToString).toList() which is also optimized for this kind of actions. More on streams see:  https://stackify.com/streams-guide-java-8/
- Didn't see a log statement in the PidTypeService instead of the comment
- Did anything happen with this comment Is this needed, the documentBuilderFactor is always null right? as it isn't initiated in HandleServiceTest. It is strange to log in a test class and especially in a constructor
- Remove the ObjectMapper on line 26 of the PidTypeServiceTest

2022-11-30 08:14 UTC, merged